name: build-release
on: workflow_dispatch

jobs:
  build-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Disable binfmt_misc shenanigans
        run:  |
              sudo wget -O /usr/bin/ape https://cosmo.zip/pub/cosmos/bin/ape-$(uname -m).elf
              sudo chmod +x /usr/bin/ape
              sudo sh -c "echo ':APE:M::MZqFpD::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"
              sudo sh -c "echo ':APE-jart:M::jartsr::/usr/bin/ape:' >/proc/sys/fs/binfmt_misc/register"

      - uses: actions/checkout@v4

      - name: Build Cosmo toolchain
        run:  tool/cosmocc/package.sh

      - name: Prepare toolchain archive
        run:  cd cosmocc && zip -ry9A ../cosmocc.zip .

      - name: Create release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run:  gh release create cosmocc_${{github.sha}}_${{github.run_id}}_${{github.run_attempt}} -t "Cosmo toolchain" cosmocc.zip
